@template.layouts.main(
title = "Kortti",
subTitle = "HTMX Demo page",
showNavigation = false,
content = @`
    <div class="grid">
        <a href="/cards">
            <article>Cards</article>
        </a>
        <a href="/memes">
            <article>Memes</article>
        </a>
        <a href="/games">
            <article>Games</article>
        </a>
        <a href="/charts">
            <article>Charts</article>
        </a>
    </div>
`)
